CREATE TYPE "public"."AuthProvider" AS ENUM('EMAIL', 'GOOGLE', 'FACEBOOK', 'APPLE');--> statement-breakpoint
CREATE TYPE "public"."AvailabilityStatus" AS ENUM('AVAILABLE', 'BUSY', 'PARTIALLY_AVAILABLE', 'UNAVAILABLE');--> statement-breakpoint
CREATE TYPE "public"."ExperienceLevel" AS ENUM('BEGINNER', 'INTERMEDIATE', 'ADVANCED', 'NATIVE');--> statement-breakpoint
CREATE TYPE "public"."Gender" AS ENUM('MALE', 'FEMALE', 'OTHER', 'PREFER_NOT_TO_SAY');--> statement-breakpoint
CREATE TYPE "public"."ProfileCompleteness" AS ENUM('BASIC', 'INTERMEDIATE', 'COMPLETE', 'PREMIUM');--> statement-breakpoint
CREATE TYPE "public"."TwoFactorMethod" AS ENUM('SMS', 'EMAIL', 'TOTP');--> statement-breakpoint
CREATE TYPE "public"."UnionStatus" AS ENUM('UNION', 'NON_UNION', 'FICORE');--> statement-breakpoint
CREATE TYPE "public"."UserRole" AS ENUM('ACTOR', 'CASTING_DIRECTOR', 'PRODUCER', 'AGENT', 'MANAGER', 'ADMIN');--> statement-breakpoint
CREATE TABLE "talents" (
	"id" text PRIMARY KEY NOT NULL,
	"userId" text NOT NULL,
	"firstName" text NOT NULL,
	"lastName" text NOT NULL,
	"middleName" text,
	"displayName" text,
	"dateOfBirth" timestamp NOT NULL,
	"gender" "Gender" NOT NULL,
	"nationality" text DEFAULT 'Indian' NOT NULL,
	"aadharNumber" text,
	"panNumber" text,
	"passportNumber" text,
	"primaryPhone" text NOT NULL,
	"secondaryPhone" text,
	"whatsappNumber" text,
	"email" text NOT NULL,
	"alternateEmail" text,
	"currentCity" text NOT NULL,
	"currentState" text NOT NULL,
	"currentPincode" text,
	"hometown" text,
	"preferredLocations" text[],
	"willingToRelocate" boolean DEFAULT false NOT NULL,
	"height" double precision,
	"weight" double precision,
	"chest" double precision,
	"waist" double precision,
	"hips" double precision,
	"shoeSize" text,
	"dressSize" text,
	"bio" text,
	"experience" jsonb,
	"yearsOfExperience" integer DEFAULT 0 NOT NULL,
	"unionStatus" "UnionStatus" DEFAULT 'NON_UNION' NOT NULL,
	"unionId" text,
	"agentId" text,
	"agencyName" text,
	"managerName" text,
	"managerContact" text,
	"actingSkills" text[],
	"danceSkills" text[],
	"martialArts" text[],
	"musicalInstruments" text[],
	"singingSkills" text[],
	"languages" text[],
	"dialects" text[],
	"accents" text[],
	"specialSkills" text[],
	"marathiProficiency" "ExperienceLevel",
	"hindiProficiency" "ExperienceLevel",
	"englishProficiency" "ExperienceLevel",
	"gujaratiProficiency" "ExperienceLevel",
	"regionalExperience" text[],
	"availabilityStatus" "AvailabilityStatus" DEFAULT 'AVAILABLE' NOT NULL,
	"availableFrom" timestamp,
	"availableTo" timestamp,
	"minimumRate" double precision,
	"maximumRate" double precision,
	"preferredRate" double precision,
	"rateNegotiable" boolean DEFAULT true NOT NULL,
	"profileImageUrl" text,
	"portfolioUrls" text[],
	"instagramHandle" text,
	"facebookProfile" text,
	"linkedinProfile" text,
	"youtubeChannel" text,
	"websiteUrl" text,
	"profileCompleteness" "ProfileCompleteness" DEFAULT 'BASIC' NOT NULL,
	"profileScore" double precision DEFAULT 0 NOT NULL,
	"isVerified" boolean DEFAULT false NOT NULL,
	"verifiedAt" timestamp,
	"verificationNotes" text,
	"embeddingId" text,
	"embeddingUpdatedAt" timestamp,
	"searchTags" text[],
	"aiGeneratedSummary" text,
	"lastAiAnalysis" timestamp,
	"rating" double precision DEFAULT 0 NOT NULL,
	"totalReviews" integer DEFAULT 0 NOT NULL,
	"totalAuditions" integer DEFAULT 0 NOT NULL,
	"totalCallbacks" integer DEFAULT 0 NOT NULL,
	"totalBookings" integer DEFAULT 0 NOT NULL,
	"responseRate" double precision DEFAULT 100 NOT NULL,
	"responseTime" integer DEFAULT 0 NOT NULL,
	"isActive" boolean DEFAULT true NOT NULL,
	"isPremium" boolean DEFAULT false NOT NULL,
	"premiumExpiresAt" timestamp,
	"lastActiveAt" timestamp DEFAULT now() NOT NULL,
	"profileViewsCount" integer DEFAULT 0 NOT NULL,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp NOT NULL,
	CONSTRAINT "talents_userId_unique" UNIQUE("userId"),
	CONSTRAINT "talents_embeddingId_unique" UNIQUE("embeddingId")
);
--> statement-breakpoint
CREATE TABLE "users" (
	"id" text PRIMARY KEY NOT NULL,
	"email" text NOT NULL,
	"emailVerified" boolean DEFAULT false NOT NULL,
	"emailVerificationToken" text,
	"emailVerificationExpires" timestamp,
	"password" text,
	"firstName" text,
	"lastName" text,
	"profileImage" text,
	"role" "UserRole" DEFAULT 'ACTOR' NOT NULL,
	"phoneNumber" text,
	"isPhoneVerified" boolean DEFAULT false NOT NULL,
	"dateOfBirth" timestamp,
	"gender" "Gender",
	"location" text,
	"bio" text,
	"isActive" boolean DEFAULT true NOT NULL,
	"lastLogin" timestamp,
	"loginCount" integer DEFAULT 0 NOT NULL,
	"authProvider" "AuthProvider" DEFAULT 'EMAIL' NOT NULL,
	"authProviderUserId" text,
	"twoFactorEnabled" boolean DEFAULT false NOT NULL,
	"twoFactorMethod" "TwoFactorMethod",
	"twoFactorBackupCodes" text[],
	"passwordResetToken" text,
	"passwordResetExpires" timestamp,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp NOT NULL,
	CONSTRAINT "users_email_unique" UNIQUE("email")
);
--> statement-breakpoint
ALTER TABLE "talents" ADD CONSTRAINT "talents_userId_users_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE cascade;