# Prometheus Configuration for CastMatch
# Production monitoring setup with comprehensive metrics

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    environment: production
    service: castmatch

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Load alerting rules
rule_files:
  - "/etc/prometheus/rules/*.yml"

# Scrape configurations
scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    metrics_path: /metrics
    scrape_interval: 15s

  # Node Exporter for system metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: 
        - 'node-exporter:9100'
    metrics_path: /metrics
    scrape_interval: 15s

  # CastMatch Backend API
  - job_name: 'castmatch-backend'
    static_configs:
      - targets:
        - 'backend:5000'
    metrics_path: /api/metrics
    scrape_interval: 15s
    scrape_timeout: 10s
    basic_auth:
      username: metrics
      password: ${METRICS_PASSWORD}

  # CastMatch Frontend (Next.js)
  - job_name: 'castmatch-frontend'
    static_configs:
      - targets:
        - 'frontend:3000'
    metrics_path: /api/metrics
    scrape_interval: 30s
    scrape_timeout: 10s

  # PostgreSQL Database
  - job_name: 'postgresql'
    static_configs:
      - targets:
        - 'postgres-exporter:9187'
    metrics_path: /metrics
    scrape_interval: 15s

  # Redis Cache
  - job_name: 'redis'
    static_configs:
      - targets:
        - 'redis-exporter:9121'
    metrics_path: /metrics
    scrape_interval: 15s

  # Nginx Load Balancer
  - job_name: 'nginx'
    static_configs:
      - targets:
        - 'nginx-exporter:9113'
    metrics_path: /metrics
    scrape_interval: 15s

  # PgBouncer Connection Pooler
  - job_name: 'pgbouncer'
    static_configs:
      - targets:
        - 'pgbouncer-exporter:9127'
    metrics_path: /metrics
    scrape_interval: 15s

  # Blackbox Exporter for external monitoring
  - job_name: 'blackbox-http'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - https://app.castmatch.com
        - https://api.castmatch.com/health
        - https://castmatch.com
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  # SSL Certificate monitoring
  - job_name: 'blackbox-ssl'
    metrics_path: /probe
    params:
      module: [tcp_connect]
    static_configs:
      - targets:
        - app.castmatch.com:443
        - api.castmatch.com:443
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  # DNS monitoring
  - job_name: 'blackbox-dns'
    metrics_path: /probe
    params:
      module: [dns_soa]
    static_configs:
      - targets:
        - castmatch.com
        - app.castmatch.com
        - api.castmatch.com
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  # OAuth provider monitoring
  - job_name: 'oauth-providers'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - https://accounts.google.com/.well-known/openid-configuration
        - https://api.github.com
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  # Custom application metrics
  - job_name: 'castmatch-custom-metrics'
    static_configs:
      - targets:
        - 'custom-metrics-exporter:8080'
    metrics_path: /metrics
    scrape_interval: 30s
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'castmatch_.*'
        target_label: service
        replacement: castmatch

# Remote write configuration for long-term storage
remote_write:
  - url: ${REMOTE_WRITE_URL}
    basic_auth:
      username: ${REMOTE_WRITE_USERNAME}
      password: ${REMOTE_WRITE_PASSWORD}
    write_relabel_configs:
      - source_labels: [__name__]
        regex: 'castmatch_.*|up|node_.*|postgres_.*|redis_.*|nginx_.*'
        action: keep

# Storage configuration
storage:
  tsdb:
    path: /prometheus
    retention.time: 30d
    retention.size: 50GB
    wal-compression: true